[tool.poetry]
name = "asynch-tikon93"
version = "0.1.10"
description = "A asyncio driver for ClickHouse with native tcp protocol"
authors = ["long2ice <long2ice@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/long2ice/asynch"
repository = "https://github.com/long2ice/asynch.git"
documentation = "https://github.com/long2ice/asynch"
keywords = ["ClickHouse", "asyncio", "driver"]
packages = [
    { include = "asynch" }
]
include = ["LICENSE", "README.md"]

[tool.poetry.dependencies]
python = "^3.7"
leb128 = "*"
pytz = "*"
lz4 = "*"
clickhouse-cityhash = "*"
zstd = "*"
tzlocal = "*"
ciso8601 = "*"

[tool.poetry.dev-dependencies]
flake8 = "*"
isort = "*"
black = "*"
pytest = "*"
pytest-mock = "*"
bandit = "*"
pytest-asyncio = "*"
clickhouse-driver = "*"
uvloop = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
